-- Fresh ENT Clinic database schema for Supabase.
-- Run this once in a new Supabase project.
-- Supabase Auth provides auth.users for email/password accounts.

create table if not exists public.patients (
    id bigint generated by default as identity primary key,
    patient_number text unique,
    first_name text not null,
    last_name text not null,
    middle_name text,
    date_of_birth date,
    sex text check (sex in ('female', 'male', 'other', 'prefer_not_to_say')),
    phone text,
    email text,
    address text,
    blood_type text,
    allergies text,
    emergency_contact_name text,
    emergency_contact_phone text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.staff (
    id uuid primary key references auth.users(id) on delete cascade,
    full_name text not null,
    role text not null check (role in ('admin', 'doctor', 'secretary')),
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

alter table public.staff add column if not exists is_active boolean not null default true;
alter table public.staff drop constraint if exists staff_role_check;
alter table public.staff add constraint staff_role_check check (role in ('admin', 'doctor', 'secretary'));

create table if not exists public.visits (
    id bigint generated by default as identity primary key,
    patient_id bigint not null references public.patients(id) on delete cascade,
    doctor_id uuid references public.staff(id) on delete set null,
    clinic_location text,
    reason text,
    blood_pressure text,
    temperature numeric(4,1),
    weight_kg numeric(5,2),
    notes text,
    status text not null default 'waiting'
        check (status in ('waiting', 'with_doctor', 'completed', 'cancelled')),
    checked_in_at timestamptz not null default now(),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists visits_patient_id_idx on public.visits(patient_id);
create index if not exists visits_doctor_id_idx on public.visits(doctor_id);
create index if not exists visits_status_idx on public.visits(status);
create index if not exists visits_checked_in_at_idx on public.visits(checked_in_at);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists patients_set_updated_at on public.patients;
create trigger patients_set_updated_at
before update on public.patients
for each row execute function public.set_updated_at();

drop trigger if exists staff_set_updated_at on public.staff;
create trigger staff_set_updated_at
before update on public.staff
for each row execute function public.set_updated_at();

drop trigger if exists visits_set_updated_at on public.visits;
create trigger visits_set_updated_at
before update on public.visits
for each row execute function public.set_updated_at();

create or replace function public.validate_visit_doctor()
returns trigger
language plpgsql
as $$
begin
    if new.doctor_id is not null and not exists (
        select 1 from public.staff
        where id = new.doctor_id and role = 'doctor'
    ) then
        raise exception 'doctor_id must reference a staff member with the doctor role';
    end if;
    return new;
end;
$$;

drop trigger if exists visits_validate_doctor on public.visits;
create trigger visits_validate_doctor
before insert or update of doctor_id on public.visits
for each row execute function public.validate_visit_doctor();

create or replace function public.create_staff_profile()
returns trigger
language plpgsql
security definer set search_path = public
as $$
declare
    selected_role text := new.raw_user_meta_data ->> 'role';
    selected_name text := coalesce(
        new.raw_user_meta_data ->> 'full_name',
        split_part(coalesce(new.email, 'New user'), '@', 1)
    );
begin
    if selected_role in ('admin', 'doctor', 'secretary') then
        insert into public.staff (id, full_name, role)
        values (new.id, selected_name, selected_role);
    end if;
    return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.create_staff_profile();

alter table public.patients enable row level security;
alter table public.staff enable row level security;
alter table public.visits enable row level security;

drop policy if exists "Authenticated users can read patients" on public.patients;
create policy "Authenticated users can read patients"
on public.patients for select to authenticated using (true);

drop policy if exists "Authenticated users can insert patients" on public.patients;
create policy "Authenticated users can insert patients"
on public.patients for insert to authenticated with check (true);

drop policy if exists "Authenticated users can update patients" on public.patients;
create policy "Authenticated users can update patients"
on public.patients for update to authenticated using (true) with check (true);

drop policy if exists "Authenticated users can delete patients" on public.patients;
create policy "Authenticated users can delete patients"
on public.patients for delete to authenticated using (true);

create or replace function public.is_admin()
returns boolean
language sql
security definer set search_path = public
stable
as $$
    select exists (
        select 1 from public.staff
        where id = auth.uid() and role = 'admin' and is_active = true
    );
$$;

drop policy if exists "Staff can read their own profile" on public.staff;
create policy "Staff can read their own profile"
on public.staff for select to authenticated using (id = auth.uid() or public.is_admin());

drop policy if exists "Staff can update their own profile" on public.staff;
create policy "Staff can update their own profile"
on public.staff for update to authenticated
using (id = auth.uid() or public.is_admin()) with check (id = auth.uid() or public.is_admin());

drop policy if exists "Authenticated users can read visits" on public.visits;
create policy "Authenticated users can read visits"
on public.visits for select to authenticated using (true);

drop policy if exists "Authenticated users can insert visits" on public.visits;
create policy "Authenticated users can insert visits"
on public.visits for insert to authenticated with check (true);

drop policy if exists "Authenticated users can update visits" on public.visits;
create policy "Authenticated users can update visits"
on public.visits for update to authenticated using (true) with check (true);

drop policy if exists "Authenticated users can delete visits" on public.visits;
create policy "Authenticated users can delete visits"
on public.visits for delete to authenticated using (true);

-- Relationships:
-- auth.users.id -> staff.id
-- patients.id -> visits.patient_id
-- staff.id -> visits.doctor_id
-- Run against the existing Supabase database before deploying the updated pages.
-- Existing patient details and visit history are retained.
begin;
-- Older databases may predate staff activation and admin role helpers.
alter table public.staff add column if not exists is_active boolean not null default true;
create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path = public
as $$
    select exists (
        select 1 from public.staff
        where id = auth.uid() and role = 'admin' and is_active = true
    );
$$;
create extension if not exists btree_gist with schema extensions;
alter table public.patients add column if not exists suffix text;
alter table public.visits add column if not exists kind text not null default 'appointment' check (kind in ('appointment', 'operation'));
alter table public.visits add column if not exists ends_at timestamptz;
alter table public.visits add column if not exists reminder_minutes integer not null default 15 check (reminder_minutes in (15, 30, 60, 1440));
alter table public.visits drop constraint if exists visits_status_check;
alter table public.visits add constraint visits_status_check check (status in ('scheduled', 'waiting', 'with_doctor', 'completed', 'cancelled'));
alter table public.visits drop constraint if exists visits_schedule_times_check;
alter table public.visits add constraint visits_schedule_times_check check (
    (ends_at is null or ends_at > checked_in_at) and
    (status <> 'scheduled' or (ends_at is not null and doctor_id is not null))
);
-- NULL end times on historical visits are not treated as reserved slots.
alter table public.visits drop constraint if exists visits_doctor_no_overlap;
alter table public.visits add constraint visits_doctor_no_overlap exclude using gist (
    doctor_id with =, tstzrange(checked_in_at, ends_at, '[)') with &&
) where (ends_at is not null and status <> 'cancelled');

create or replace function public.clinic_role()
returns text language sql stable security definer set search_path = public
as $$ select role from public.staff where id = auth.uid() and is_active = true $$;

-- Staff may not promote themselves or reactivate their own accounts.
drop policy if exists "Staff can update their own profile" on public.staff;
create policy "Staff can update their own profile" on public.staff for update to authenticated
using (public.is_admin()) with check (public.is_admin());
drop policy if exists "Staff can read their own profile" on public.staff;
create policy "Staff can read their own profile" on public.staff for select to authenticated
using (id = auth.uid() or public.is_admin() or (public.clinic_role() in ('doctor', 'secretary') and role = 'doctor' and is_active));

-- Replace the original broad policies, so doctor views are read only at the database too.
drop policy if exists "Authenticated users can read patients" on public.patients;
create policy "Authenticated users can read patients" on public.patients for select to authenticated using (public.clinic_role() in ('admin', 'doctor', 'secretary'));
drop policy if exists "Authenticated users can insert patients" on public.patients;
create policy "Authenticated users can insert patients" on public.patients for insert to authenticated with check (public.clinic_role() in ('admin', 'secretary'));
drop policy if exists "Authenticated users can update patients" on public.patients;
create policy "Authenticated users can update patients" on public.patients for update to authenticated using (public.clinic_role() in ('admin', 'secretary')) with check (public.clinic_role() in ('admin', 'secretary'));
drop policy if exists "Authenticated users can delete patients" on public.patients;
create policy "Authenticated users can delete patients" on public.patients for delete to authenticated using (public.is_admin());
drop policy if exists "Authenticated users can read visits" on public.visits;
create policy "Authenticated users can read visits" on public.visits for select to authenticated using (public.clinic_role() in ('admin', 'doctor', 'secretary'));
drop policy if exists "Authenticated users can insert visits" on public.visits;
create policy "Authenticated users can insert visits" on public.visits for insert to authenticated with check (public.clinic_role() in ('admin', 'secretary'));
drop policy if exists "Authenticated users can update visits" on public.visits;
create policy "Authenticated users can update visits" on public.visits for update to authenticated using (public.clinic_role() in ('admin', 'secretary')) with check (public.clinic_role() in ('admin', 'secretary'));
drop policy if exists "Authenticated users can delete visits" on public.visits;
create policy "Authenticated users can delete visits" on public.visits for delete to authenticated using (public.is_admin());

create or replace function public.validate_booking()
returns trigger language plpgsql set search_path = public
as $$
begin
    if new.status = 'scheduled' then
        if not exists (select 1 from public.staff where id = new.doctor_id and role = 'doctor' and is_active) then
            raise exception 'Select an active doctor';
        end if;
        if TG_OP = 'INSERT' then
            if new.checked_in_at <= now() then raise exception 'Choose a future appointment time'; end if;
        elsif new.checked_in_at is distinct from old.checked_in_at and new.checked_in_at <= now() then
            raise exception 'Choose a future appointment time';
        end if;
    end if;
    return new;
end;
$$;
drop trigger if exists visits_validate_booking on public.visits;
create trigger visits_validate_booking before insert or update on public.visits for each row execute function public.validate_booking();
commit;

-- Run after 20260912_scheduling_roles.sql. Existing appointments are retained.
begin;
alter table public.visits drop constraint if exists visits_kind_check;
alter table public.visits add constraint visits_kind_check check (kind in ('appointment', 'operation', 'event'));
alter table public.visits alter column patient_id drop not null;
alter table public.visits drop constraint if exists visits_patient_required;
alter table public.visits add constraint visits_patient_required check (kind = 'event' or patient_id is not null);
alter table public.visits drop constraint if exists visits_event_status_check;
alter table public.visits add constraint visits_event_status_check check (kind <> 'event' or status in ('scheduled', 'completed', 'cancelled'));
commit;

-- Run after the scheduling and event migrations. Enables live schedule updates.
begin;
do $$
begin
    if not exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
        create publication supabase_realtime;
    end if;
    if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'visits') then
        alter publication supabase_realtime add table public.visits;
    end if;
end;
$$;
commit;

-- Requires all previous scheduling migrations. Never expose service_role credentials to the app.
begin;
create table if not exists public.push_devices (
    token text primary key,
    user_id uuid not null references public.staff(id) on delete cascade,
    updated_at timestamptz not null default now()
);
alter table public.push_devices enable row level security;
drop policy if exists "Doctors manage their own push devices" on public.push_devices;
create policy "Doctors manage their own push devices" on public.push_devices for all to authenticated
using (user_id = auth.uid() and public.clinic_role() = 'doctor')
with check (user_id = auth.uid() and public.clinic_role() = 'doctor');
grant select, insert, update, delete on public.push_devices to authenticated;
create index if not exists push_devices_user_idx on public.push_devices(user_id);
create table if not exists public.schedule_push_jobs (
    id bigint generated always as identity primary key,
    visit_id bigint not null references public.visits(id) on delete cascade,
    user_id uuid not null references public.staff(id) on delete cascade,
    category text not null check (category in ('change','reminder')),
    scheduled_start timestamptz not null,
    run_at timestamptz not null,
    expires_at timestamptz not null,
    attempts integer not null default 0,
    locked_until timestamptz,
    sent_tokens text[] not null default '{}',
    finished_at timestamptz
);
alter table public.schedule_push_jobs enable row level security;
grant all on public.push_devices, public.schedule_push_jobs to service_role;
grant usage, select on sequence public.schedule_push_jobs_id_seq to service_role;
-- No authenticated policies: only the server's service role can access jobs.
create index if not exists schedule_push_due_idx on public.schedule_push_jobs(run_at) where finished_at is null;
create or replace function public.enqueue_schedule_push()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
    if TG_OP = 'UPDATE' and row(new.kind,new.doctor_id,new.checked_in_at,new.ends_at,new.status,new.reason,new.clinic_location,new.reminder_minutes,new.patient_id)
        is not distinct from row(old.kind,old.doctor_id,old.checked_in_at,old.ends_at,old.status,old.reason,old.clinic_location,old.reminder_minutes,old.patient_id) then return new; end if;
    -- Superseded reminders and unsent changes are invalidated on edits or cancellations.
    delete from public.schedule_push_jobs where visit_id = new.id and finished_at is null;
    if new.kind in ('operation','event') and new.doctor_id is not null then
        insert into public.schedule_push_jobs(visit_id,user_id,category,scheduled_start,run_at,expires_at)
        values(new.id,new.doctor_id,'change',new.checked_in_at,now(),now()+interval '1 day');
        if new.status = 'scheduled' and new.ends_at > now() then
            insert into public.schedule_push_jobs(visit_id,user_id,category,scheduled_start,run_at,expires_at)
            values(new.id,new.doctor_id,'reminder',new.checked_in_at,greatest(now(),new.checked_in_at-make_interval(mins=>new.reminder_minutes)),new.ends_at);
        end if;
    end if;
    return new;
end;
$$;
drop trigger if exists visits_enqueue_schedule_push on public.visits;
create trigger visits_enqueue_schedule_push after insert or update on public.visits for each row execute function public.enqueue_schedule_push();
create or replace function public.claim_schedule_push_jobs()
returns setof public.schedule_push_jobs language sql security definer set search_path = public
as $$
    update public.schedule_push_jobs set locked_until = now()+interval '5 minutes', attempts = attempts+1
    where id in (
        select id from public.schedule_push_jobs
        where finished_at is null and run_at <= now() and expires_at > now() and attempts < 8
          and (locked_until is null or locked_until < now())
        order by run_at for update skip locked limit 10
    ) returning *;
$$;
revoke all on function public.claim_schedule_push_jobs() from public, anon, authenticated;
grant execute on function public.claim_schedule_push_jobs() to service_role;
revoke all on public.schedule_push_jobs from anon, authenticated;
-- Backfill upcoming operations/events, without generating historical change alerts.
insert into public.schedule_push_jobs(visit_id,user_id,category,scheduled_start,run_at,expires_at)
select v.id,v.doctor_id,'reminder',v.checked_in_at,greatest(now(),v.checked_in_at-make_interval(mins=>v.reminder_minutes)),v.ends_at
from public.visits v where v.kind in ('operation','event') and v.status='scheduled' and v.doctor_id is not null and v.ends_at > now()
and not exists(select 1 from public.schedule_push_jobs j where j.visit_id=v.id and j.category='reminder' and j.scheduled_start=v.checked_in_at);
commit;

-- Run after the existing migrations. If duplicate identities exist, this transaction
-- stops without changing records. Review them before retrying; never auto-delete patients.
begin;
create or replace function public.patient_name_key(value text)
returns text language sql immutable strict parallel safe
as $$ select lower(regexp_replace(btrim(value), '[[:space:]]+', ' ', 'g')) $$;

create unique index if not exists patients_name_birthdate_unique
on public.patients (public.patient_name_key(first_name), public.patient_name_key(last_name), date_of_birth)
where date_of_birth is not null;

alter table public.patients add column if not exists record_pictures jsonb not null default '[]'::jsonb;
create or replace function public.valid_patient_pictures(pictures jsonb)
returns boolean language plpgsql immutable as $$
declare picture jsonb;
begin
    if jsonb_typeof(pictures) <> 'array' then return false; end if;
    if jsonb_array_length(pictures) > 4 then return false; end if;
    for picture in select value from jsonb_array_elements(pictures) loop
        if jsonb_typeof(picture) <> 'string' or length(picture #>> '{}') > 1500000
           or (picture #>> '{}') !~ '^data:image/jpeg;base64,[A-Za-z0-9+/]+={0,2}$' then return false; end if;
    end loop;
    return true;
end;
$$;
alter table public.patients add constraint patients_record_pictures_valid check (public.valid_patient_pictures(record_pictures));

create or replace function public.validate_patient_identity()
returns trigger language plpgsql as $$
begin
    if btrim(new.first_name) = '' or btrim(new.last_name) = '' then
        raise exception 'First and last names are required';
    end if;
    if TG_OP = 'INSERT' and new.date_of_birth is null then
        raise exception 'Date of birth is required';
    end if;
    if new.date_of_birth > current_date then raise exception 'Date of birth cannot be in the future'; end if;
    return new;
end;
$$;
create trigger patients_validate_identity before insert or update of first_name, last_name, date_of_birth
on public.patients for each row execute function public.validate_patient_identity();
commit;

-- Run after the existing scheduling/role migrations. Preserves existing visits.
begin;
create table if not exists public."Notes" (
    id bigint generated always as identity primary key,
    visit_id bigint not null unique references public.visits(id) on delete restrict,
    patient_id bigint not null references public.patients(id) on delete restrict,
    doctor_id uuid not null references public.staff(id) on delete restrict,
    subjective text not null default '',
    objective text not null default '',
    history text not null default '',
    assessment text not null default '',
    plan text not null default '',
    rx text not null default '',
    referral text not null default '',
    recommendation text not null default '',
    admitting_orders text not null default '',
    pf text not null default '',
    diagnostic text not null default '',
    created_at timestamptz not null default now(),
    constraint notes_not_empty check (length(btrim(subjective || objective || history || assessment || plan || rx || referral || recommendation || admitting_orders || pf || diagnostic)) > 0)
);
create index if not exists notes_patient_idx on public."Notes" (patient_id);
alter table public."Notes" enable row level security;
revoke all on public."Notes" from anon, authenticated;
grant select on public."Notes" to authenticated;
grant all on public."Notes" to service_role;
grant usage, select on sequence public."Notes_id_seq" to service_role;
drop policy if exists "Doctors read their consultation notes" on public."Notes";
create policy "Doctors read their consultation notes" on public."Notes" for select to authenticated
using ((public.clinic_role() = 'doctor' and doctor_id = auth.uid()) or public.is_admin());

create or replace function public.accept_consultation(p_visit_id bigint)
returns bigint language plpgsql security definer set search_path = public as $$
declare v public.visits%rowtype;
begin
    if public.clinic_role() is distinct from 'doctor' then raise exception 'Only an active doctor can accept a patient'; end if;
    select * into v from public.visits where id = p_visit_id for update;
    if not found or v.doctor_id is distinct from auth.uid() or v.kind <> 'appointment' then
        raise exception 'This consultation is not assigned to you';
    end if;
    if v.status not in ('waiting', 'with_doctor') then raise exception 'This patient is no longer waiting for consultation'; end if;
    if v.status = 'waiting' then update public.visits set status = 'with_doctor' where id = v.id; end if;
    return v.id;
end;
$$;

create or replace function public.save_consultation_notes(p_visit_id bigint, p_notes jsonb)
returns bigint language plpgsql security definer set search_path = public as $$
declare
    v public.visits%rowtype;
    existing public."Notes"%rowtype;
    note_id bigint;
    field_name text;
    normalized jsonb := '{}'::jsonb;
    fields text[] := array['subjective','objective','history','assessment','plan','rx','referral','recommendation','admitting_orders','pf','diagnostic'];
begin
    if public.clinic_role() is distinct from 'doctor' then raise exception 'Only an active doctor can save consultation notes'; end if;
    if p_notes is null or jsonb_typeof(p_notes) <> 'object' then raise exception 'Notes must be an object'; end if;
    foreach field_name in array fields loop
        if p_notes ? field_name and jsonb_typeof(p_notes -> field_name) <> 'string' then raise exception 'Note fields must be text'; end if;
        if length(coalesce(p_notes ->> field_name, '')) > 20000 then raise exception 'Each note field must be at most 20000 characters'; end if;
        normalized := normalized || jsonb_build_object(field_name, btrim(coalesce(p_notes ->> field_name, '')));
    end loop;
    if not exists (select 1 from jsonb_each_text(normalized) where value <> '') then raise exception 'Enter consultation notes before saving'; end if;
    select * into v from public.visits where id = p_visit_id for update;
    if not found or v.doctor_id is distinct from auth.uid() or v.kind <> 'appointment' then raise exception 'This consultation is not assigned to you'; end if;
    select * into existing from public."Notes" where visit_id = v.id;
    if found then
        -- A retry after a lost response succeeds, but a second tab cannot overwrite a saved note.
        if existing.doctor_id = auth.uid() and v.status = 'completed' and
            (to_jsonb(existing) - array['id','visit_id','patient_id','doctor_id','created_at']) = normalized then return existing.id; end if;
        raise exception 'Notes have already been saved. Reopen the consultation to view them';
    end if;
    if v.status <> 'with_doctor' then raise exception 'Accept this patient before saving consultation notes'; end if;
    insert into public."Notes" (visit_id, patient_id, doctor_id, subjective, objective, history, assessment, plan, rx, referral, recommendation, admitting_orders, pf, diagnostic)
    values (v.id, v.patient_id, auth.uid(), normalized->>'subjective', normalized->>'objective', normalized->>'history',
        normalized->>'assessment', normalized->>'plan', normalized->>'rx', normalized->>'referral', normalized->>'recommendation', normalized->>'admitting_orders', normalized->>'pf', normalized->>'diagnostic')
    returning id into note_id;
    update public.visits set status = 'completed' where id = v.id;
    return note_id;
end;
$$;

-- Keep visit identity and completed notes together, and prevent skipping the consultation flow.
create or replace function public.guard_consultation_workflow()
returns trigger language plpgsql security definer set search_path = public as $$
begin
    if exists (select 1 from public."Notes" where visit_id = old.id) then
        if row(new.patient_id,new.doctor_id,new.kind,new.status) is distinct from row(old.patient_id,old.doctor_id,old.kind,'completed'::text) then
            raise exception 'A saved consultation cannot be reopened or reassigned';
        end if;
    elsif new.kind = 'appointment' and new.status is distinct from old.status then
        if new.status = 'completed' then raise exception 'Save consultation notes to complete this visit'; end if;
        if new.status = 'with_doctor' and (public.clinic_role() is distinct from 'doctor' or new.doctor_id is distinct from auth.uid()) then
            raise exception 'The assigned doctor must accept this patient';
        end if;
    end if;
    return new;
end;
$$;
drop trigger if exists visits_guard_consultation on public.visits;
create trigger visits_guard_consultation before update on public.visits for each row execute function public.guard_consultation_workflow();
revoke all on function public.accept_consultation(bigint), public.save_consultation_notes(bigint,jsonb) from public, anon;
grant execute on function public.accept_consultation(bigint), public.save_consultation_notes(bigint,jsonb) to authenticated;
commit;

-- Run after 20260913_consultation_notes.sql. Allows the assigned doctor to edit saved notes.
begin;
create or replace function public.update_consultation_notes(p_visit_id bigint, p_notes jsonb, p_expected_notes jsonb)
returns bigint language plpgsql security definer set search_path = public as $$
declare
    v public.visits%rowtype;
    saved public."Notes"%rowtype;
    current_notes jsonb;
    normalized jsonb := '{}'::jsonb;
    field_name text;
    fields text[] := array['subjective','objective','history','assessment','plan','rx','referral','recommendation','admitting_orders','pf','diagnostic'];
begin
    if public.clinic_role() is distinct from 'doctor' then raise exception 'Only an active doctor can edit consultation notes'; end if;
    if p_notes is null or jsonb_typeof(p_notes) <> 'object' then raise exception 'Notes must be an object'; end if;
    foreach field_name in array fields loop
        if not (p_notes ? field_name) or jsonb_typeof(p_notes -> field_name) <> 'string' then raise exception 'All note fields must be text'; end if;
        if length(p_notes ->> field_name) > 20000 then raise exception 'Each note field must be at most 20000 characters'; end if;
        normalized := normalized || jsonb_build_object(field_name, btrim(p_notes ->> field_name));
    end loop;
    if not exists (select 1 from jsonb_each_text(normalized) where value <> '') then raise exception 'Enter consultation notes before saving'; end if;
    select * into v from public.visits where id = p_visit_id for update;
    if not found or v.doctor_id is distinct from auth.uid() or v.kind <> 'appointment' or v.status <> 'completed' then
        raise exception 'This completed consultation is not assigned to you';
    end if;
    select * into saved from public."Notes" where visit_id = v.id for update;
    if not found or saved.doctor_id is distinct from auth.uid() then raise exception 'Saved notes not found for this doctor'; end if;
    current_notes := to_jsonb(saved) - array['id','visit_id','patient_id','doctor_id','created_at'];
    -- Identical retries succeed; stale forms cannot overwrite another saved change.
    if current_notes = normalized then return saved.id; end if;
    if p_expected_notes is distinct from current_notes then raise exception 'These notes changed in another window. Copy your changes, reopen the consultation, and review the latest notes'; end if;
    update public."Notes" set subjective=normalized->>'subjective', objective=normalized->>'objective',
        history=normalized->>'history', assessment=normalized->>'assessment', plan=normalized->>'plan',
        rx=normalized->>'rx', referral=normalized->>'referral', recommendation=normalized->>'recommendation',
        admitting_orders=normalized->>'admitting_orders', pf=normalized->>'pf', diagnostic=normalized->>'diagnostic'
    where id = saved.id;
    return saved.id;
end;
$$;
revoke all on function public.update_consultation_notes(bigint,jsonb,jsonb) from public, anon;
grant execute on function public.update_consultation_notes(bigint,jsonb,jsonb) to authenticated;
commit;

-- Cancellation permanently deletes the visit/schedule, not the patient.
-- Run after the consultation notes migrations.
begin;
create or replace function public.cancel_visit(p_visit_id bigint, p_expected_status text)
returns bigint language plpgsql security definer set search_path = public as $$
declare v public.visits%rowtype;
begin
    if public.clinic_role() is null or public.clinic_role() not in ('secretary', 'admin') then
        raise exception 'Only a secretary or administrator can cancel a visit';
    end if;
    if p_expected_status is null or p_expected_status not in ('waiting', 'scheduled') then
        raise exception 'Only waiting or scheduled visits can be cancelled';
    end if;
    select * into v from public.visits where id = p_visit_id for update;
    if not found then return p_visit_id; end if;
    if v.status is distinct from p_expected_status then
        raise exception 'This visit has changed. Refresh the queue or schedule before cancelling';
    end if;
    -- The Notes foreign key also prevents deleting a visit with saved clinical notes.
    delete from public.visits where id = v.id;
    return v.id;
end;
$$;
revoke all on function public.cancel_visit(bigint,text) from public, anon;
grant execute on function public.cancel_visit(bigint,text) to authenticated;

-- Remove existing cancelled visits. Linked push jobs are removed by their FK cascade.
-- If a cancelled visit has saved Notes, its restrictive FK stops this transaction.
delete from public.visits where status = 'cancelled';
notify pgrst, 'reload schema';
commit;

-- Run in Supabase SQL Editor after the patient identity/pictures migration.
begin;
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('PatientRecordUploads', 'PatientRecordUploads', false, 10485760, array['image/jpeg', 'image/png', 'image/webp'])
on conflict (id) do update set public = false, file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Clinic staff read patient pictures" on storage.objects;
create policy "Clinic staff read patient pictures" on storage.objects for select to authenticated
using (bucket_id = 'PatientRecordUploads' and public.clinic_role() in ('admin', 'doctor', 'secretary'));
drop policy if exists "Registration staff upload patient pictures" on storage.objects;
create policy "Registration staff upload patient pictures" on storage.objects for insert to authenticated
with check (bucket_id = 'PatientRecordUploads' and public.clinic_role() in ('admin', 'secretary')
    and name ~ '^records/[0-9a-f-]{36}[.]jpg$');

-- Keep existing embedded photos readable while new uploads use object paths.
create or replace function public.valid_patient_pictures(pictures jsonb)
returns boolean language plpgsql immutable as $$
declare picture jsonb; value text;
begin
    if jsonb_typeof(pictures) <> 'array' then return false; end if;
    if jsonb_array_length(pictures) > 4 then return false; end if;
    for picture in select * from jsonb_array_elements(pictures) loop
        value := picture #>> '{}';
        if jsonb_typeof(picture) <> 'string' or length(value) > 1500000 then return false; end if;
        if value !~ '^data:image/jpeg;base64,[A-Za-z0-9+/]+={0,2}$'
           and value !~ '^records/[0-9a-f-]{36}[.]jpg$' then return false; end if;
    end loop;
    return true;
end;
$$;
commit;

-- Allow active secretaries to read saved consultation notes in patient profiles.
-- Editing remains restricted to the assigned doctor through existing RPCs.
begin;
drop policy if exists "Secretaries read consultation notes" on public."Notes";
create policy "Secretaries read consultation notes"
on public."Notes" for select to authenticated
using (public.clinic_role() = 'secretary');
commit;

begin;
-- Never trust public sign-up metadata for staff permissions.
create or replace function public.create_staff_profile()
returns trigger language plpgsql security definer set search_path = public
as $$
declare
    selected_role text := new.raw_app_meta_data ->> 'role';
    selected_name text := coalesce(nullif(trim(new.raw_user_meta_data ->> 'full_name'), ''), split_part(coalesce(new.email, 'New user'), '@', 1));
begin
    if selected_role in ('admin', 'doctor', 'secretary') then
        insert into public.staff (id, full_name, role) values (new.id, selected_name, selected_role);
    end if;
    return new;
end;
$$;
-- Preserve doctor attribution on existing visits.
alter table public.visits drop constraint if exists visits_doctor_id_fkey;
alter table public.visits add constraint visits_doctor_id_fkey
    foreign key (doctor_id) references public.staff(id) on delete restrict;
commit;
