-- ENT Clinic database: 01 core schema
-- Run before the other database scripts.

-- Fresh ENT Clinic database schema for Supabase.
-- Run this once in a new Supabase project.
-- Supabase Auth provides auth.users for email/password accounts.

create table if not exists public.patients (
    id bigint generated by default as identity primary key,
    patient_number text unique,
    first_name text not null,
    last_name text not null,
    middle_name text,
    date_of_birth date,
    sex text check (sex in ('female', 'male', 'other', 'prefer_not_to_say')),
    phone text,
    email text,
    address text,
    blood_type text,
    allergies text,
    emergency_contact_name text,
    emergency_contact_phone text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.staff (
    id uuid primary key references auth.users(id) on delete cascade,
    full_name text not null,
    role text not null check (role in ('admin', 'doctor', 'secretary')),
    is_active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

alter table public.staff add column if not exists is_active boolean not null default true;
alter table public.staff drop constraint if exists staff_role_check;
alter table public.staff add constraint staff_role_check check (role in ('admin', 'doctor', 'secretary'));

create table if not exists public.visits (
    id bigint generated by default as identity primary key,
    patient_id bigint not null references public.patients(id) on delete cascade,
    doctor_id uuid references public.staff(id) on delete set null,
    clinic_location text,
    reason text,
    blood_pressure text,
    temperature numeric(4,1),
    weight_kg numeric(5,2),
    notes text,
    status text not null default 'waiting'
        check (status in ('waiting', 'with_doctor', 'completed', 'cancelled')),
    checked_in_at timestamptz not null default now(),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists visits_patient_id_idx on public.visits(patient_id);
create index if not exists visits_doctor_id_idx on public.visits(doctor_id);
create index if not exists visits_status_idx on public.visits(status);
create index if not exists visits_checked_in_at_idx on public.visits(checked_in_at);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists patients_set_updated_at on public.patients;
create trigger patients_set_updated_at
before update on public.patients
for each row execute function public.set_updated_at();

drop trigger if exists staff_set_updated_at on public.staff;
create trigger staff_set_updated_at
before update on public.staff
for each row execute function public.set_updated_at();

drop trigger if exists visits_set_updated_at on public.visits;
create trigger visits_set_updated_at
before update on public.visits
for each row execute function public.set_updated_at();

create or replace function public.validate_visit_doctor()
returns trigger
language plpgsql
as $$
begin
    if new.doctor_id is not null and not exists (
        select 1 from public.staff
        where id = new.doctor_id and role = 'doctor'
    ) then
        raise exception 'doctor_id must reference a staff member with the doctor role';
    end if;
    return new;
end;
$$;

drop trigger if exists visits_validate_doctor on public.visits;
create trigger visits_validate_doctor
before insert or update of doctor_id on public.visits
for each row execute function public.validate_visit_doctor();

create or replace function public.create_staff_profile()
returns trigger
language plpgsql
security definer set search_path = public
as $$
declare
    selected_role text := new.raw_user_meta_data ->> 'role';
    selected_name text := coalesce(
        new.raw_user_meta_data ->> 'full_name',
        split_part(coalesce(new.email, 'New user'), '@', 1)
    );
begin
    if selected_role in ('admin', 'doctor', 'secretary') then
        insert into public.staff (id, full_name, role)
        values (new.id, selected_name, selected_role);
    end if;
    return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.create_staff_profile();

alter table public.patients enable row level security;
alter table public.staff enable row level security;
alter table public.visits enable row level security;

drop policy if exists "Authenticated users can read patients" on public.patients;
create policy "Authenticated users can read patients"
on public.patients for select to authenticated using (true);

drop policy if exists "Authenticated users can insert patients" on public.patients;
create policy "Authenticated users can insert patients"
on public.patients for insert to authenticated with check (true);

drop policy if exists "Authenticated users can update patients" on public.patients;
create policy "Authenticated users can update patients"
on public.patients for update to authenticated using (true) with check (true);

drop policy if exists "Authenticated users can delete patients" on public.patients;
create policy "Authenticated users can delete patients"
on public.patients for delete to authenticated using (true);

create or replace function public.is_admin()
returns boolean
language sql
security definer set search_path = public
stable
as $$
    select exists (
        select 1 from public.staff
        where id = auth.uid() and role = 'admin' and is_active = true
    );
$$;

drop policy if exists "Staff can read their own profile" on public.staff;
create policy "Staff can read their own profile"
on public.staff for select to authenticated using (id = auth.uid() or public.is_admin());

drop policy if exists "Staff can update their own profile" on public.staff;
create policy "Staff can update their own profile"
on public.staff for update to authenticated
using (id = auth.uid() or public.is_admin()) with check (id = auth.uid() or public.is_admin());

drop policy if exists "Authenticated users can read visits" on public.visits;
create policy "Authenticated users can read visits"
on public.visits for select to authenticated using (true);

drop policy if exists "Authenticated users can insert visits" on public.visits;
create policy "Authenticated users can insert visits"
on public.visits for insert to authenticated with check (true);

drop policy if exists "Authenticated users can update visits" on public.visits;
create policy "Authenticated users can update visits"
on public.visits for update to authenticated using (true) with check (true);

drop policy if exists "Authenticated users can delete visits" on public.visits;
create policy "Authenticated users can delete visits"
on public.visits for delete to authenticated using (true);

-- Relationships:
-- auth.users.id -> staff.id
-- patients.id -> visits.patient_id
-- staff.id -> visits.doctor_id
